In [2]:
import numpy as np

In [5]:
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
             [4,5,6,7]])

In [9]:
d = np.zeros((2,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
e = np.random.rand(2,5)

In [11]:
print(e)

[[0.68488111 0.71856296 0.22077368 0.87465219 0.17376789]
 [0.94234535 0.4539726  0.96829249 0.48177559 0.03402944]]


In [12]:
print(a * b)

[ 0  5 12 21]


In [13]:
print( a * c)

[[ 0  1  4  9]
 [ 0  5 12 21]]
