In [1]:
import numpy as np

In [2]:
a = np.zeros((2,4))
b = np.zeros((4,3))
c = a.dot(b)
print(c.shape)

(2, 3)


In [3]:
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e